# Generated by Django 4.1.4 on 2022-12-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Cart1',
        ),
    ]
