# Generated by Django 4.1.4 on 2022-12-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0002_rename_cart_cart1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart1',
            name='car_name',
        ),
    ]
