# Generated by Django 4.1.4 on 2022-12-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0003_remove_cart1_car_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart1',
            name='cart_id',
        ),
    ]
