# Generated by Django 4.1.4 on 2022-12-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0004_remove_cart1_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart1',
            name='car_name',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='carApp.car'),
            preserve_default=False,
        ),
    ]
