# Generated by Django 4.1.4 on 2022-12-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0007_alter_cart1_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart1',
            name='car_id',
        ),
    ]
