# Generated by Django 4.1.4 on 2022-12-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0008_remove_cart1_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart1',
            name='car_name',
        ),
        migrations.AddField(
            model_name='cart1',
            name='car_id',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart1',
            name='cart_id',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
