# Generated by Django 4.1.4 on 2022-12-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0009_remove_cart1_car_name_cart1_car_id_cart1_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart1',
            name='car_id',
        ),
        migrations.AddField(
            model_name='cart1',
            name='car_name',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
    ]
