# Generated by Django 4.1.4 on 2022-12-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0011_remove_cart1_car_name_remove_cart1_cart_id_cart1_car_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_color',
        ),
        migrations.AddField(
            model_name='car',
            name='brand_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='color_id',
            field=models.IntegerField(null=True),
        ),
    ]
