# Generated by Django 4.1.4 on 2022-12-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0014_rename_brand_id_car_brand_id1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand_id1',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='color_id2',
            new_name='color',
        ),
    ]
